### ISSUE TITLE
Sugestão de melhoria no arquivo

### ISSUE THREAD

**Issue by isa-carvalho** [danncastro/site-reliability-engineering#1]
Gostaria de colaborar no seu repositorio de estudo e indicar que adicione mais arquivos, relacionados a SRE .

**Comment by danncastro** [comment]
Olá Isabella, seja bem vinda ao mundo de tecnologia, espero que esteja gostando, obrigado pela sua solicitação de melhoria, vou validar meus repositorios, e gostaria que me enviasse novos Feedbacks caso encontre algo de novo.
